name: vigilancia_perte_manual
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  
    
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 
        
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: excute py script
        env: 
          CODA__API__KEY: ${{ secrets.CODA__API__KEY }}
        run: python run.py
